config/routes.rb
Rails.application.routes.draw do
  resources :presents
  resources :vue
  resources :hotwire
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/present.rb
class Present < ApplicationRecord

  # broadcasts_to -> (present) { "presents" }
  after_create_commit { byebug }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hotwire_controller.rb
class HotwireController < ApplicationController

  def index
    @presents = Present.all
  end

  def create
    @present = Present.new(present_params)

    respond_to do |format|
      if @present.save
        format.json { render json: @present, status: :created }
      else
        format.json { render json: @present, status: :unprocessable_entity }
      end
    end
  end

  private

    def present_params
      params.permit(:name, :image_path)
    end

end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController

  def index
    @presents = Present.all
  end

  def new
    byebug
  end

  def create
    @present = Present.new(present_params)

    respond_to do |format|
      if @present.save
        format.json { render json: @present, status: :created }
      else
        format.json { render json: @present, status: :unprocessable_entity }
      end
    end
  end

  private

    def present_params
      params.permit(:name, :image_path)
    end

end

app/controllers/vue_controller.rb
class VueController < ApplicationController

  def index
    @presents = Present.all
  end

  def new
    byebug
  end

  def create
    @present = Present.new(present_params)

    respond_to do |format|
      if @present.save
        format.json { render json: @present, status: :created }
      else
        format.json { render json: @present, status: :unprocessable_entity }
      end
    end
  end

  private

    def present_params
      params.permit(:name, :image_path)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/views/hotwire/index.html.erb
<%= turbo_stream_from @presents %>

<%= turbo_frame_tag "presents" do %>
  <%= render @presents %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wishlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%# = javascript_pack_tag 'application' %>
    <%= yield :head %>
    <%= turbo_include_tags %>
    <%= stimulus_include_tags %>
  </head>

  <body>
    <div class="container mx-auto">
      <%= yield %>
    </div>
  </body>
</html>

app/views/presents/_present.html.erb
<%#= present.name  %>
Something

app/views/presents/create.turbo_stream.erb
<%= turbo_stream.append "presents", @present %>

app/views/presents/index.html.erb
<turbo-stream action="append" target="presents">
  <template>
  </template>
</turbo-stream>

app/views/vue/index.html.erb
<div data-behavior="vue">
  <app
    inline-template
    :presents="<%= @presents.to_json %>"
    >
    <div>
      <h1 class="font-sans text-6xl text-center my-10 subpixel-antialiased tracking-wider">Wishlist</h1>
      <vue-form
        v-slot="formProps"
        class="md:max-w-3xl flex justify-center mx-auto mb-8" 
        :form-url="<%= presents_path.to_json %>"
        :form-action=<%= "POST".to_json %>
        :submit-action="getImage"
        :on-success="addPresent"
      >
        <div class="w-full">
          <input 
            v-model="formProps.model.name"
            class="block w-full px-4 py-3 mb-8 text-base appearance-none border-b border-gray-300 shadow-none bg-white placeholder-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300"
            placeholder="Search">
          </input>
        </div>
      </vue-form>

      <div>
        <presents :presents="allPresents" :placeholder="'<%= asset_path('xbox') %>'"></presents>
      </div>
    </div>
  </app>
</div>